### ISSUE TITLE
Program crashes right after showing main window.

### ISSUE THREAD

**Issue by deMathias** [adamk33n3r/PathOfExileStashSorter#1]
latest release, never used it before.

Unzipping into another folder just gives the same result. The program worked once. Is it writing something in appdata or local maybe ?

![sorter](https://user-images.githubusercontent.com/47175867/120186687-1c9b3400-c214-11eb-8e48-3312a1f2bb23.gif)

**Comment by anzenchitai** [comment]
Can't even launch. Getting a 403 forbidden.

**Comment by adamk33n3r** [comment]
@deMathias I did add icon caching that stores them in `AppData\Roaming\PoEStashSorter\Cache`. Why do you ask?

@anzenchitai Can you elaborate? Are you using your correct session id?

**Comment by adamk33n3r** [comment]
I have added a new RC https://github.com/adamk33n3r/PathOfExileStashSorter/releases/tag/v3.14-rc.3 that should make the error more visible by showing a messagebox when it happens.

@anzenchitai another thing I thought of, is your profile private on the website? The app currently fetches your characters without the token, so it's getting them through the public permissions. For example, you can see my characters here https://www.pathofexile.com/account/view-profile/adamk33n3r/characters. If you don't have that enabled then that would make sense that it would cause a 403 for you. Go to https://www.pathofexile.com/account/view-profile/{{YOUR ACCOUNT NAME}}/privacy and check if your character tab is hidden. If it is, if you uncheck that then I think it will work as a temporary solution. I understand some people would like to keep that hidden, so I will try to fix that for next time by using the secure endpoint.

**Comment by deMathias** [comment]
> @deMathias I did add icon caching that stores them in `AppData\Roaming\PoEStashSorter\Cache`. Why do you ask?
> 
> @anzenchitai Can you elaborate? Are you using your correct session id?

I asked because unzipping the program in a different folder yields the same results, making me think it is trying to load something from appdata. I will try the new release.

**Comment by deMathias** [comment]
@adamk33n3r the new release actually spews out an error as you said it would:

![image](https://user-images.githubusercontent.com/47175867/120657749-119b0a80-c485-11eb-8017-2582d06c1591.png)

thanks for looking into this.

**Comment by adamk33n3r** [comment]
@deMathias aha! That's super helpful! It looks like it's erroring because one or more of your tabs have a slash in it. This normally wouldn't be an issue, but it looks like I accidentally left in some debug code that dumps your stash contents to files. Because of this, it's interpreting that slash in the stash name as part of the path as a new directory. So that's why it's erroring. I will try to push out a fix for that but in the meantime if you could try removing slashes from your stash tab names and see if that temporarily fixes it that'd be great. I see in the screenshot that it's just the default name for sell tabs so I apologize that this didn't get caught in my testing.

**Comment by deMathias** [comment]
@adamk33n3r Adam, glad it was of help. But it is still a mistery for me why it didn't error the very first launch, since i haven't change tab names. It actually sorted an entire tab for me before it started crashing.

**Comment by adamk33n3r** [comment]
@deMathias it's because you had switched to that tab. It uses the tab name for the file path when you have that tab selected. Anyway, here's the fix https://github.com/adamk33n3r/PathOfExileStashSorter/releases/tag/v3.14-rc.4 Let me know if this works for ya!

**Comment by deMathias** [comment]
@adamk33n3r the crashing is fixed, but now it won't start sorting anymore. Opened another ticket. #2 Thanks a lot for your work!
